//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_ssrs_report
    {
        public int ssrs_report_skey { get; set; }
        public string ssrs_report_description { get; set; }
        public string ssrs_report_name { get; set; }
        public Nullable<bool> ssrs_report_name_spanish_flag { get; set; }
        public int ssrs_report_type_skey { get; set; }
        public int servicing_step_skey { get; set; }
        public string ssrs_procedure_name { get; set; }
        public Nullable<int> state_required_step_skey { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
