//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_product_type
    {
        public int product_type_skey { get; set; }
        public string product_type_description { get; set; }
        public int product_type_category_skey { get; set; }
        public Nullable<decimal> assignment_percent { get; set; }
        public Nullable<short> sequence__number { get; set; }
        public Nullable<int> minimum_borrower_age { get; set; }
        public Nullable<decimal> maximum_change_of_plan_fee_amount { get; set; }
        public Nullable<decimal> minimum_expected_interest_rate { get; set; }
        public Nullable<decimal> maximum_expected_interest_rate { get; set; }
        public Nullable<int> minimum_rescission_days { get; set; }
        public Nullable<int> tenure_age { get; set; }
        public int growth_method_skey { get; set; }
        public Nullable<decimal> growth_rate { get; set; }
        public Nullable<bool> allow_change_of_plan_flag { get; set; }
        public Nullable<bool> calculate_sfsa_flag { get; set; }
        public Nullable<decimal> minimum_disbursement_amount { get; set; }
        public Nullable<decimal> minimum_loan_amount { get; set; }
        public Nullable<decimal> maximum_loan_amount { get; set; }
        public Nullable<decimal> minimum_service_fee_amount { get; set; }
        public Nullable<decimal> maximum_service_fee_amount { get; set; }
        public Nullable<decimal> servicing_fee_margin { get; set; }
        public Nullable<decimal> initial_mip_percent { get; set; }
        public Nullable<decimal> alternate_initial_mip_percent { get; set; }
        public Nullable<decimal> maximum_pl_percent_for_std_imip { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
