//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_search_column
    {
        public int search_column_skey { get; set; }
        public int search_window_skey { get; set; }
        public string search_column_name { get; set; }
        public string order_by_expression { get; set; }
    }
}
