//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_letter_default_value
    {
        public int letter_default_value_skey { get; set; }
        public int client_skey { get; set; }
        public string letter_job_type { get; set; }
        public string default_representative { get; set; }
        public Nullable<int> default_toll_free_number { get; set; }
        public string default_servicer_name { get; set; }
        public string default_servicer_address1 { get; set; }
        public string default_servicer_address2 { get; set; }
        public string default_servicer_city { get; set; }
        public string default_servicer_state { get; set; }
        public string default_servicer_zip_code { get; set; }
        public string default_alternate_name { get; set; }
        public string default_alternate_address1 { get; set; }
        public string default_alternate_address2 { get; set; }
        public string default_alternate_city { get; set; }
        public string default_alternate_state { get; set; }
        public string default_alternate_zip_code { get; set; }
        public string default_hours_of_operation { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
