//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_qc_criteria
    {
        public int qc_criteria_skey { get; set; }
        public string qc_criteria_description { get; set; }
        public string column_name { get; set; }
        public string column_type { get; set; }
        public Nullable<int> column_group_id { get; set; }
        public string justification { get; set; }
        public string update_table_name { get; set; }
        public string update_column_name { get; set; }
        public bool is_large_flag { get; set; }
        public string column_data_type { get; set; }
        public Nullable<int> column_data_size { get; set; }
        public Nullable<int> column_height { get; set; }
        public string column_edit_mask { get; set; }
        public string column_display_format { get; set; }
        public string dddw_name { get; set; }
        public string dddw_display_column_name { get; set; }
        public string dddw_data_column_name { get; set; }
        public string stg_column_name { get; set; }
        public bool is_remove_punctuation_flag { get; set; }
        public bool is_remove_punctuation_needed_flag { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
