//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_product_arm_rate_index_type
    {
        public int product_arm_rate_index_type_skey { get; set; }
        public int product_type_skey { get; set; }
        public string arm_type { get; set; }
        public int rate_index_type_skey { get; set; }
        public string hmbs_pool_type { get; set; }
        public Nullable<decimal> margin { get; set; }
        public Nullable<decimal> lifetime_cap_from_closing_rate { get; set; }
        public Nullable<decimal> change_maximum_from_closing_rate { get; set; }
        public Nullable<decimal> change_maximum_from_current_rate { get; set; }
        public Nullable<int> first_rate_change_days_minimum { get; set; }
        public Nullable<int> first_rate_change_days_maximum { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
