//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_transaction_code
    {
        public string transaction_code { get; set; }
        public string short_transaction_description { get; set; }
        public string long_transaction_description { get; set; }
        public int transaction_category_skey { get; set; }
        public Nullable<bool> accrue_interest_flag { get; set; }
        public string transaction_type { get; set; }
        public string transaction_column { get; set; }
        public string transaction_origin { get; set; }
        public string transaction_sign { get; set; }
        public string adjust_transaction_code { get; set; }
        public string trigger_transaction_code { get; set; }
        public Nullable<bool> include_in_unscheduled_loan_balance_flag { get; set; }
        public Nullable<bool> is_reverse_eboutique_transaction_flag { get; set; }
        public Nullable<bool> allow_user_to_adjust_flag { get; set; }
        public Nullable<bool> allow_partial_adjustment_flag { get; set; }
        public Nullable<bool> is_setup_transaction_flag { get; set; }
        public Nullable<bool> is_tax_type_flag { get; set; }
        public Nullable<bool> is_insurance_type_flag { get; set; }
        public Nullable<bool> requires_additional_description_flag { get; set; }
        public string eboutique_code { get; set; }
        public string hmbs_payment_reason_code { get; set; }
        public string loan_sub_status_code { get; set; }
        public string boa_payoff_code { get; set; }
        public string boa_export_code { get; set; }
        public string HUD_export_code { get; set; }
        public Nullable<int> loc_account_money_movement_code { get; set; }
        public Nullable<int> cab_account_money_movement_code { get; set; }
        public Nullable<int> cai_account_money_movement_code { get; set; }
        public Nullable<int> car_account_money_movement_code { get; set; }
        public Nullable<int> cas_account_money_movement_code { get; set; }
        public Nullable<int> loss_draft_account_money_movement_code { get; set; }
        public Nullable<int> loc_ach_account_money_movement_code { get; set; }
        public Nullable<int> cab_ach_account_money_movement_code { get; set; }
        public Nullable<int> cai_ach_account_money_movement_code { get; set; }
        public Nullable<int> car_ach_account_money_movement_code { get; set; }
        public Nullable<int> cas_ach_account_money_movement_code { get; set; }
        public Nullable<int> loss_draft_ach_account_money_movement_code { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
