//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_disbursement_payee_type
    {
        public int payee_type_skey { get; set; }
        public string payee_description { get; set; }
        public bool invoice_required_flag { get; set; }
        public bool merge_checks_flag { get; set; }
        public string dddw_name { get; set; }
        public string dddw_label { get; set; }
        public string dddw_data_column_name { get; set; }
        public string dddw_display_column_name { get; set; }
        public string dddw_retrieval_arg { get; set; }
        public string dddw_filter { get; set; }
        public string dddw_width { get; set; }
        public string dddw_allow_edit { get; set; }
        public string information_dddw_name { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
