//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_investor
    {
        public int investor_skey { get; set; }
        public string investor_name { get; set; }
        public int loan_servicer_skey { get; set; }
        public string alternate_name { get; set; }
        public string legal_name { get; set; }
        public string legal_name_part1 { get; set; }
        public string legal_name_part2 { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state_code { get; set; }
        public string zip_code { get; set; }
        public Nullable<decimal> main_phone_number { get; set; }
        public Nullable<decimal> alt_phone_number { get; set; }
        public Nullable<decimal> fax_number { get; set; }
        public string email { get; set; }
        public string website_url { get; set; }
        public decimal max_check_shortage_amount { get; set; }
        public decimal max_check_overage_amount { get; set; }
        public string check_payable_to { get; set; }
        public string correspondence_department { get; set; }
        public string correspondence_contact { get; set; }
        public string funds_received_by_time { get; set; }
        public Nullable<bool> requires_private_label_flag { get; set; }
        public Nullable<int> letter_logo_height { get; set; }
        public Nullable<int> letter_logo_width { get; set; }
        public string letter_logo_filetype { get; set; }
        public Nullable<int> report_logo_height { get; set; }
        public Nullable<int> report_logo_width { get; set; }
        public string report_logo_filetype { get; set; }
        public string signature_filetype { get; set; }
        public byte[] letter_logo_image { get; set; }
        public byte[] report_logo_image { get; set; }
        public byte[] signature_image { get; set; }
        public string ftp_folder { get; set; }
        public string ftp_filename { get; set; }
        public Nullable<int> flow_loan_pool_skey { get; set; }
        public string processed_folder { get; set; }
        public string hmbs_issuer_skey { get; set; }
        public string fannie_mae_servicer_number { get; set; }
        public Nullable<int> first_sch_pay_cutoff_day { get; set; }
        public string tax_id_number { get; set; }
        public Nullable<bool> request_funds_in_advance_flag { get; set; }
        public Nullable<decimal> min_refund_amount { get; set; }
        public Nullable<bool> include_overage_transaction_flag { get; set; }
        public string hmbs_check_digit { get; set; }
        public string fha_mortgagee_number { get; set; }
        public Nullable<bool> HUD_setup_flag { get; set; }
        public Nullable<bool> is_FNMA_flag { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
