//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_hmbs_transaction_code
    {
        public string hmbs_transaction_code { get; set; }
        public string short_transaction_description { get; set; }
        public string long_transaction_description { get; set; }
        public Nullable<int> hmbs_transaction_category_skey { get; set; }
        public string transaction_column { get; set; }
        public string transaction_sign { get; set; }
        public bool allow_user_to_adjust_flag { get; set; }
        public string adjust_transaction_code { get; set; }
        public string hmbs_payment_reason_code { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
