//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_ssrs_report_type
    {
        public int ssrs_report_type_skey { get; set; }
        public string ssrs_report_type_description { get; set; }
        public Nullable<int> ssrs_servicing_type_skey { get; set; }
        public string ssrs_report_contact_types { get; set; }
        public string ssrs_default_reason_skeys { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
