//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuestWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReverseQuestEntities : DbContext
    {
        public ReverseQuestEntities()
            : base("name=ReverseQuestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ref_age_equivalency> ref_age_equivalency { get; set; }
        public virtual DbSet<ref_alert_severity> ref_alert_severity { get; set; }
        public virtual DbSet<ref_alert_type> ref_alert_type { get; set; }
        public virtual DbSet<ref_app_parameter> ref_app_parameter { get; set; }
        public virtual DbSet<ref_arm_type> ref_arm_type { get; set; }
        public virtual DbSet<ref_auto_job> ref_auto_job { get; set; }
        public virtual DbSet<ref_auto_note> ref_auto_note { get; set; }
        public virtual DbSet<ref_bank_routing> ref_bank_routing { get; set; }
        public virtual DbSet<ref_bankruptcy_district> ref_bankruptcy_district { get; set; }
        public virtual DbSet<ref_batch_status> ref_batch_status { get; set; }
        public virtual DbSet<ref_batch_type> ref_batch_type { get; set; }
        public virtual DbSet<ref_county_mortgage_limit> ref_county_mortgage_limit { get; set; }
        public virtual DbSet<ref_disbursement_type> ref_disbursement_type { get; set; }
        public virtual DbSet<ref_document_category> ref_document_category { get; set; }
        public virtual DbSet<ref_document_type> ref_document_type { get; set; }
        public virtual DbSet<ref_email_template> ref_email_template { get; set; }
        public virtual DbSet<ref_flood_zone> ref_flood_zone { get; set; }
        public virtual DbSet<ref_hmbs_issuer> ref_hmbs_issuer { get; set; }
        public virtual DbSet<ref_hmbs_servicing_fee_type> ref_hmbs_servicing_fee_type { get; set; }
        public virtual DbSet<ref_investor_bank_account> ref_investor_bank_account { get; set; }
        public virtual DbSet<ref_LESA_type> ref_LESA_type { get; set; }
        public virtual DbSet<ref_letter_default_value> ref_letter_default_value { get; set; }
        public virtual DbSet<ref_loan_channel> ref_loan_channel { get; set; }
        public virtual DbSet<ref_loan_originator> ref_loan_originator { get; set; }
        public virtual DbSet<ref_loan_status> ref_loan_status { get; set; }
        public virtual DbSet<ref_loan_sub_status> ref_loan_sub_status { get; set; }
        public virtual DbSet<ref_log_message_type> ref_log_message_type { get; set; }
        public virtual DbSet<ref_map_servicer_document_type> ref_map_servicer_document_type { get; set; }
        public virtual DbSet<ref_note_type> ref_note_type { get; set; }
        public virtual DbSet<ref_note_type_category> ref_note_type_category { get; set; }
        public virtual DbSet<ref_payment_plan_status> ref_payment_plan_status { get; set; }
        public virtual DbSet<ref_payment_plan_type> ref_payment_plan_type { get; set; }
        public virtual DbSet<ref_payment_status> ref_payment_status { get; set; }
        public virtual DbSet<ref_property_type> ref_property_type { get; set; }
        public virtual DbSet<ref_property_type_category> ref_property_type_category { get; set; }
        public virtual DbSet<ref_property_value_sub_type> ref_property_value_sub_type { get; set; }
        public virtual DbSet<ref_property_value_type> ref_property_value_type { get; set; }
        public virtual DbSet<ref_qc_criteria> ref_qc_criteria { get; set; }
        public virtual DbSet<ref_qc_criteria_product> ref_qc_criteria_product { get; set; }
        public virtual DbSet<ref_qc_document_type> ref_qc_document_type { get; set; }
        public virtual DbSet<ref_qc_sub_status> ref_qc_sub_status { get; set; }
        public virtual DbSet<ref_rate_index_type> ref_rate_index_type { get; set; }
        public virtual DbSet<ref_rff_group> ref_rff_group { get; set; }
        public virtual DbSet<ref_rff_type> ref_rff_type { get; set; }
        public virtual DbSet<ref_search_column> ref_search_column { get; set; }
        public virtual DbSet<ref_search_window> ref_search_window { get; set; }
        public virtual DbSet<ref_ssrs_report> ref_ssrs_report { get; set; }
        public virtual DbSet<ref_ssrs_report_type> ref_ssrs_report_type { get; set; }
        public virtual DbSet<ref_status> ref_status { get; set; }
        public virtual DbSet<ref_workflow_category> ref_workflow_category { get; set; }
        public virtual DbSet<ref_workflow_category_client_config> ref_workflow_category_client_config { get; set; }
        public virtual DbSet<ref_workflow_conflict> ref_workflow_conflict { get; set; }
        public virtual DbSet<ref_workflow_task> ref_workflow_task { get; set; }
        public virtual DbSet<ref_workflow_task_category> ref_workflow_task_category { get; set; }
        public virtual DbSet<ref_workflow_task_client_config> ref_workflow_task_client_config { get; set; }
        public virtual DbSet<ref_workflow_task_result> ref_workflow_task_result { get; set; }
        public virtual DbSet<ref_workflow_task_result_xref> ref_workflow_task_result_xref { get; set; }
        public virtual DbSet<ref_workflow_task_trigger> ref_workflow_task_trigger { get; set; }
        public virtual DbSet<ref_workflow_type> ref_workflow_type { get; set; }
        public virtual DbSet<ref_workflow_type_client_config> ref_workflow_type_client_config { get; set; }
        public virtual DbSet<ref_workflow_type_default_reason> ref_workflow_type_default_reason { get; set; }
        public virtual DbSet<ref_zip_county> ref_zip_county { get; set; }
        public virtual DbSet<ref_business_day> ref_business_day { get; set; }
        public virtual DbSet<ref_client> ref_client { get; set; }
        public virtual DbSet<ref_contact_type> ref_contact_type { get; set; }
        public virtual DbSet<ref_county_clerk> ref_county_clerk { get; set; }
        public virtual DbSet<ref_default_reason> ref_default_reason { get; set; }
        public virtual DbSet<ref_default_status> ref_default_status { get; set; }
        public virtual DbSet<ref_denial_reason> ref_denial_reason { get; set; }
        public virtual DbSet<ref_disbursement_payee_type> ref_disbursement_payee_type { get; set; }
        public virtual DbSet<ref_eboutique_loan_status_maintenance> ref_eboutique_loan_status_maintenance { get; set; }
        public virtual DbSet<ref_growth_method> ref_growth_method { get; set; }
        public virtual DbSet<ref_hmbs_custodian> ref_hmbs_custodian { get; set; }
        public virtual DbSet<ref_hmbs_transaction_category> ref_hmbs_transaction_category { get; set; }
        public virtual DbSet<ref_hmbs_transaction_code> ref_hmbs_transaction_code { get; set; }
        public virtual DbSet<ref_investor> ref_investor { get; set; }
        public virtual DbSet<ref_investor_disbursement_type> ref_investor_disbursement_type { get; set; }
        public virtual DbSet<ref_language_preference> ref_language_preference { get; set; }
        public virtual DbSet<ref_loan_boarding_validation_mapping> ref_loan_boarding_validation_mapping { get; set; }
        public virtual DbSet<ref_loan_boarding_validation_rules> ref_loan_boarding_validation_rules { get; set; }
        public virtual DbSet<ref_loan_pool> ref_loan_pool { get; set; }
        public virtual DbSet<ref_loan_servicer> ref_loan_servicer { get; set; }
        public virtual DbSet<ref_map_interest_rate_type> ref_map_interest_rate_type { get; set; }
        public virtual DbSet<ref_marital_status> ref_marital_status { get; set; }
        public virtual DbSet<ref_product_arm_rate_index_type> ref_product_arm_rate_index_type { get; set; }
        public virtual DbSet<ref_product_payment_plan_type> ref_product_payment_plan_type { get; set; }
        public virtual DbSet<ref_product_type> ref_product_type { get; set; }
        public virtual DbSet<ref_product_type_category> ref_product_type_category { get; set; }
        public virtual DbSet<ref_product_type_workflow_type> ref_product_type_workflow_type { get; set; }
        public virtual DbSet<ref_remit_category> ref_remit_category { get; set; }
        public virtual DbSet<ref_remit_type> ref_remit_type { get; set; }
        public virtual DbSet<ref_reporting_period> ref_reporting_period { get; set; }
        public virtual DbSet<ref_residency_status> ref_residency_status { get; set; }
        public virtual DbSet<ref_state> ref_state { get; set; }
        public virtual DbSet<ref_tax_authority> ref_tax_authority { get; set; }
        public virtual DbSet<ref_tax_authority_type> ref_tax_authority_type { get; set; }
        public virtual DbSet<ref_tax_note_code> ref_tax_note_code { get; set; }
        public virtual DbSet<ref_tax_payment> ref_tax_payment { get; set; }
        public virtual DbSet<ref_transaction_adjustment_reason> ref_transaction_adjustment_reason { get; set; }
        public virtual DbSet<ref_transaction_category> ref_transaction_category { get; set; }
        public virtual DbSet<ref_transaction_code> ref_transaction_code { get; set; }
        public virtual DbSet<ref_transaction_column> ref_transaction_column { get; set; }
        public virtual DbSet<ref_transaction_origin> ref_transaction_origin { get; set; }
        public virtual DbSet<ref_transaction_source> ref_transaction_source { get; set; }
        public virtual DbSet<ref_transaction_type> ref_transaction_type { get; set; }
        public virtual DbSet<ref_vendor> ref_vendor { get; set; }
        public virtual DbSet<ref_vendor_type> ref_vendor_type { get; set; }
    }
}
