//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_hmbs_transaction
    {
        public long hmbs_transaction_skey { get; set; }
        public int hmbs_pool_skey { get; set; }
        public int loan_skey { get; set; }
        public string hmbs_transaction_code { get; set; }
        public System.DateTime transaction_date { get; set; }
        public System.DateTime effective_date { get; set; }
        public decimal security_principal_amount { get; set; }
        public decimal security_interest_amount { get; set; }
        public decimal gross_service_fee_amount { get; set; }
        public decimal guaranty_fee_amount { get; set; }
        public Nullable<long> reference_transaction_group_id { get; set; }
        public Nullable<long> hmbs_transaction_group_id { get; set; }
        public Nullable<long> hmbs_reference_transaction_group_id { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
