//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_property_master
    {
        public int loan_skey { get; set; }
        public int property_type_skey { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state_code { get; set; }
        public string zip_code { get; set; }
        public Nullable<int> county_clerk_skey { get; set; }
        public Nullable<int> number_of_units { get; set; }
        public int flood_zone_skey { get; set; }
        public Nullable<bool> requires_flood_insurance_flag { get; set; }
        public string flood_certificate_number { get; set; }
        public Nullable<int> flood_insurance_company_skey { get; set; }
        public Nullable<bool> life_of_loan_policy_flag { get; set; }
        public Nullable<bool> owner_occupied_flag { get; set; }
        public Nullable<System.DateTime> occupancy_date { get; set; }
        public Nullable<System.DateTime> vacancy_date { get; set; }
        public string legal_description { get; set; }
        public string folio_number { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
