//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_contact_master
    {
        public int contact_skey { get; set; }
        public Nullable<int> loan_skey { get; set; }
        public int contact_type_skey { get; set; }
        public string other_contact_type_description { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string ssn { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<System.DateTime> death_date { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state_code { get; set; }
        public string zip_code { get; set; }
        public Nullable<decimal> home_phone_number { get; set; }
        public Nullable<decimal> work_phone_number { get; set; }
        public Nullable<decimal> cell_phone_number { get; set; }
        public Nullable<decimal> fax_number { get; set; }
        public string email { get; set; }
        public string mail_first_name { get; set; }
        public string mail_middle_name { get; set; }
        public string mail_last_name { get; set; }
        public string mail_address1 { get; set; }
        public string mail_address2 { get; set; }
        public string mail_city { get; set; }
        public string mail_state_code { get; set; }
        public string mail_zip_code { get; set; }
        public Nullable<int> marital_status_skey { get; set; }
        public int language_preference_skey { get; set; }
        public string company_name { get; set; }
        public string mail_company_name { get; set; }
        public int residency_status_skey { get; set; }
        public Nullable<bool> emergency_contact_flag { get; set; }
        public Nullable<bool> authorized_contact_flag { get; set; }
        public Nullable<bool> enbs_indicator { get; set; }
        public Nullable<int> parent_contact_skey { get; set; }
        public Nullable<bool> legal_owner_flag { get; set; }
        public Nullable<bool> right_to_occupy_flag { get; set; }
        public Nullable<bool> divorced_flag { get; set; }
        public string mortgagee_optional_election { get; set; }
        public Nullable<bool> email_preferred_flag { get; set; }
        public Nullable<System.Guid> user_skey { get; set; }
        public Nullable<System.DateTime> banko_bankruptcy_sent_to_date { get; set; }
        public int signature_image_type_skey { get; set; }
        public byte[] contact_signature_image { get; set; }
        public Nullable<int> status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
