//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_loan_master
    {
        public int loan_skey { get; set; }
        public int parent_loan_skey { get; set; }
        public int loan_servicer_skey { get; set; }
        public int investor_skey { get; set; }
        public int loan_pool_skey { get; set; }
        public Nullable<int> loan_originator_skey { get; set; }
        public string investor_loan_number { get; set; }
        public string original_loan_number { get; set; }
        public string fha_case_number { get; set; }
        public string mers_min_number { get; set; }
        public string ginnie_mae_number { get; set; }
        public Nullable<int> last_participation_id { get; set; }
        public string loan_status { get; set; }
        public string loan_sub_status_code { get; set; }
        public int product_type_skey { get; set; }
        public string boarding_type { get; set; }
        public string adp_code { get; set; }
        public Nullable<System.DateTime> fha_case_number_assigned_date { get; set; }
        public Nullable<System.DateTime> closing_date { get; set; }
        public Nullable<System.DateTime> funded_date { get; set; }
        public Nullable<System.DateTime> mortgage_insurance_certified_date { get; set; }
        public string credit_type { get; set; }
        public Nullable<decimal> maximum_claim_amount { get; set; }
        public int payment_plan_type { get; set; }
        public int payment_status_skey { get; set; }
        public Nullable<int> payments_remain { get; set; }
        public Nullable<decimal> monthly_principal_amount { get; set; }
        public Nullable<decimal> monthly_principal_adjustment_amount { get; set; }
        public Nullable<decimal> monthly_service_fee_amount { get; set; }
        public Nullable<decimal> monthly_tax_escrow_amount { get; set; }
        public Nullable<System.DateTime> first_payment_date { get; set; }
        public Nullable<decimal> sch_pymt_funds_req_amount { get; set; }
        public Nullable<System.DateTime> sch_pymt_funds_req_date { get; set; }
        public Nullable<bool> print_statements_flag { get; set; }
        public Nullable<bool> rsa_includes_administration_fee_flag { get; set; }
        public Nullable<decimal> origination_fee_amount { get; set; }
        public Nullable<decimal> closing_fee_amount { get; set; }
        public Nullable<decimal> lien_payoff_amount { get; set; }
        public Nullable<decimal> total_mandatory_obligation_amount { get; set; }
        public Nullable<decimal> idl_amount { get; set; }
        public Nullable<System.DateTime> idl_expiration_date { get; set; }
        public int LESA_type { get; set; }
        public Nullable<decimal> LESA_first_year_tax_insurance_amount { get; set; }
        public Nullable<System.DateTime> LESA_next_schpay_date { get; set; }
        public int LESA_payment_status_skey { get; set; }
        public Nullable<decimal> LESA_semiannual_amount { get; set; }
        public Nullable<decimal> LESA_schedule_pay_funds_request_amount { get; set; }
        public Nullable<System.DateTime> LESA_schedule_pay_funds_request_date { get; set; }
        public string loan_manager { get; set; }
        public string tax_monitoring_contract_type { get; set; }
        public string tax_monitoring_contract_number { get; set; }
        public Nullable<System.DateTime> transfer_effective_date { get; set; }
        public Nullable<System.DateTime> hud_sent_to_date { get; set; }
        public Nullable<System.DateTime> payoff_date { get; set; }
        public Nullable<bool> prohibit_all_correspondence_flag { get; set; }
        public string custom_message { get; set; }
        public Nullable<bool> custom_message_clear_flag { get; set; }
        public Nullable<int> prior_servicer_skey { get; set; }
        public string prior_servicer_loan_number { get; set; }
        public string prior_servicer_sub_status { get; set; }
        public int loan_channel_skey { get; set; }
        public Nullable<bool> no_growth { get; set; }
        public Nullable<decimal> growth_amount { get; set; }
        public Nullable<int> scheduled_payment_day { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> hmbs_servicing_fee_type_skey { get; set; }
        public Nullable<decimal> hmbs_servicing_fee_margin { get; set; }
        public Nullable<System.DateTime> hmbs_purchase_event_date { get; set; }
    }
}
