//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_check
    {
        public int check_skey { get; set; }
        public int check_number { get; set; }
        public decimal check_amount { get; set; }
        public int number_disbursements { get; set; }
        public Nullable<int> loan_skey { get; set; }
        public int disbursement_type_skey { get; set; }
        public int payee_type_skey { get; set; }
        public Nullable<int> payee_skey { get; set; }
        public string pay_to { get; set; }
        public string payor_fractional_numerator { get; set; }
        public string payor_fractional_denominator { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> printed_date { get; set; }
        public string printed_by { get; set; }
        public Nullable<System.DateTime> cleared_date { get; set; }
        public string cleared_by { get; set; }
        public Nullable<System.DateTime> voided_date { get; set; }
        public string voided_by { get; set; }
        public Nullable<System.DateTime> payment_stopped_date { get; set; }
        public string payment_stopped_by { get; set; }
    }
}
