//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_workflow_instance
    {
        public int workflow_instance_skey { get; set; }
        public int loan_skey { get; set; }
        public int workflow_type_skey { get; set; }
        public Nullable<int> workflow_task_skey { get; set; }
        public string workflow_manager_id { get; set; }
        public string workflow_of_record_flag { get; set; }
        public Nullable<System.DateTime> default_date { get; set; }
        public Nullable<System.DateTime> due_and_payable_date { get; set; }
        public Nullable<int> default_reason_skey { get; set; }
        public Nullable<int> denial_reason_skey { get; set; }
        public Nullable<int> vendor_skey { get; set; }
        public Nullable<int> attorney_skey { get; set; }
        public Nullable<int> petitioner_skey { get; set; }
        public string case_number { get; set; }
        public string insurance_policy_number { get; set; }
        public string insurance_policy_holder { get; set; }
        public string insurance_company_name { get; set; }
        public string insurance_agent_name { get; set; }
        public string insurance_address1 { get; set; }
        public string insurance_address2 { get; set; }
        public string insurance_city { get; set; }
        public string insurance_state_code { get; set; }
        public string insurance_zip_code { get; set; }
        public Nullable<int> insurance_phone_number { get; set; }
        public Nullable<int> insurance_fax_number { get; set; }
        public string insurance_email { get; set; }
        public string insurance_website_url { get; set; }
        public Nullable<decimal> insurance_premium_amount { get; set; }
        public Nullable<decimal> coverage_amount { get; set; }
        public Nullable<decimal> repair_set_aside_amount { get; set; }
        public Nullable<System.DateTime> repair_completion_due_date { get; set; }
        public string repair_type { get; set; }
        public Nullable<int> appraiser_skey { get; set; }
        public string repayment_plan_type { get; set; }
        public Nullable<decimal> repayment_plan_amount { get; set; }
        public Nullable<int> repayment_plan_term { get; set; }
        public Nullable<decimal> transferred_property_charges_balance { get; set; }
        public Nullable<int> parent_workflow_instance_skey { get; set; }
        public string certified_letter_article_number { get; set; }
        public string comments { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
