//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_workflow_task_activity
    {
        public long workflow_task_activity_skey { get; set; }
        public int workflow_instance_skey { get; set; }
        public int workflow_task_skey { get; set; }
        public string responsible_party_id { get; set; }
        public System.DateTime original_schedule_date { get; set; }
        public System.DateTime schedule_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<System.DateTime> complete_date { get; set; }
        public Nullable<int> workflow_task_reason_skey { get; set; }
        public Nullable<int> workflow_task_result_skey { get; set; }
        public string task_note { get; set; }
        public Nullable<long> parent_activity_skey { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
