//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_hmbs_pool
    {
        public int hmbs_pool_skey { get; set; }
        public int alert_type_skey { get; set; }
        public string hmbs_pool_number { get; set; }
        public string hmbs_pool_description { get; set; }
        public string hmbs_issuer_id { get; set; }
        public string pool_tax_id { get; set; }
        public string hmbs_pool_type { get; set; }
        public System.DateTime issue_date { get; set; }
        public Nullable<System.DateTime> settlement_date { get; set; }
        public Nullable<decimal> original_aggregate_amount { get; set; }
        public Nullable<decimal> lowest_rate { get; set; }
        public Nullable<decimal> highest_rate { get; set; }
        public Nullable<decimal> security_rate { get; set; }
        public Nullable<decimal> security_margin { get; set; }
        public Nullable<decimal> annual_cap { get; set; }
        public Nullable<decimal> lifetime_cap { get; set; }
        public Nullable<int> participation_count { get; set; }
        public string cert_agreement_status { get; set; }
        public string sent_11711_indicator { get; set; }
        public string index_type { get; set; }
        public Nullable<int> hmbs_custodian_skey { get; set; }
        public Nullable<System.DateTime> balance_as_of_date { get; set; }
        public string balance_by { get; set; }
        public string hmbs_check_digit { get; set; }
        public Nullable<bool> is_certified_flag { get; set; }
        public Nullable<bool> is_final_certified_flag { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
