//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_loan_remit
    {
        public long loan_remit_skey { get; set; }
        public long loan_remit_header_skey { get; set; }
        public int loan_skey { get; set; }
        public int contact_skey { get; set; }
        public int remit_type_skey { get; set; }
        public string remit_by { get; set; }
        public decimal remit_amount { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string reference_number { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
