//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_transaction_setaside
    {
        public long transaction_setaside_skey { get; set; }
        public int loan_skey { get; set; }
        public string transaction_code { get; set; }
        public System.DateTime transaction_date { get; set; }
        public System.DateTime effective_date { get; set; }
        public decimal tax_escrow_amount { get; set; }
        public decimal service_fee_set_aside_amount { get; set; }
        public decimal first_year_set_aside_amount { get; set; }
        public decimal repair_set_aside_amount { get; set; }
        public decimal loss_draft_amount { get; set; }
        public decimal LESA_amount { get; set; }
        public Nullable<int> disbursement_skey { get; set; }
        public Nullable<int> servicing_management_skey { get; set; }
        public long transaction_group_id { get; set; }
        public Nullable<long> reference_transaction_group_id { get; set; }
        public Nullable<int> transaction_adjustment_reason_skey { get; set; }
        public Nullable<long> check_attachment_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> workflow_instance_skey { get; set; }
        public Nullable<long> check_document_skey { get; set; }
    }
}
