//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_disbursement
    {
        public int disbursement_skey { get; set; }
        public int disbursement_type_skey { get; set; }
        public int loan_skey { get; set; }
        public string pay_to { get; set; }
        public int payee_skey { get; set; }
        public string payee_type { get; set; }
        public int payee_type_skey { get; set; }
        public string payee_company_name { get; set; }
        public string payor_aba_number { get; set; }
        public string payor_account_number { get; set; }
        public string payor_fractional_numerator { get; set; }
        public string payor_fractional_denominator { get; set; }
        public Nullable<int> check_skey { get; set; }
        public int check_number { get; set; }
        public decimal check_amount { get; set; }
        public Nullable<long> check_attachment_skey { get; set; }
        public string transaction_code { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string invoice_number { get; set; }
        public Nullable<System.DateTime> incurred_date { get; set; }
        public Nullable<long> invoice_attachment_skey { get; set; }
        public string check_note { get; set; }
        public System.DateTime process_date { get; set; }
        public string voided_by { get; set; }
        public Nullable<System.DateTime> voided_date { get; set; }
        public Nullable<System.DateTime> void_requested_date { get; set; }
        public string funds_requested_by { get; set; }
        public Nullable<System.DateTime> funds_requested_date { get; set; }
        public string printed_by { get; set; }
        public Nullable<System.DateTime> printed_date { get; set; }
        public string payment_stopped_by { get; set; }
        public Nullable<System.DateTime> payment_stopped_date { get; set; }
        public string cleared_by { get; set; }
        public Nullable<System.DateTime> cleared_date { get; set; }
        public string recoverable_from { get; set; }
        public Nullable<bool> display_balance_flag { get; set; }
        public Nullable<bool> do_not_aggregate_flag { get; set; }
        public Nullable<bool> payee_includes_borrower_flag { get; set; }
        public Nullable<bool> send_to_hud_flag { get; set; }
        public Nullable<bool> estimated_flag { get; set; }
        public Nullable<int> replaced_disbursement_skey { get; set; }
        public Nullable<int> servicing_management_skey { get; set; }
        public Nullable<bool> reimbursable_flag { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public string transaction_description { get; set; }
        public Nullable<int> workflow_instance_skey { get; set; }
        public Nullable<long> check_document_skey { get; set; }
        public Nullable<long> invoice_document_skey { get; set; }
    }
}
