//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_loan_remit_header
    {
        public long loan_remit_header_skey { get; set; }
        public int loan_skey { get; set; }
        public string transaction_code { get; set; }
        public System.DateTime effective_date { get; set; }
        public decimal apply_principal_amount { get; set; }
        public decimal apply_interest_amount { get; set; }
        public decimal apply_mip_amount { get; set; }
        public decimal apply_service_fee_amount { get; set; }
        public decimal apply_corporate_advance_borrower_amount { get; set; }
        public decimal apply_corporate_advance_investor_amount { get; set; }
        public decimal apply_servicer_expense_amount { get; set; }
        public decimal apply_overage_amount { get; set; }
        public decimal apply_loss_draft_amount { get; set; }
        public decimal total_remittance_amount { get; set; }
        public Nullable<int> servicing_management_skey { get; set; }
        public Nullable<int> total_repays_to_process { get; set; }
        public Nullable<bool> exclude_accruals_flag { get; set; }
        public Nullable<bool> use_user_preference_flag { get; set; }
        public Nullable<int> batch_skey { get; set; }
        public Nullable<long> transaction_group_id { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> workflow_instance_skey { get; set; }
    }
}
