//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_loan_rate
    {
        public int loan_skey { get; set; }
        public string arm_type { get; set; }
        public int rate_index_type_skey { get; set; }
        public Nullable<System.DateTime> first_arm_change_date { get; set; }
        public Nullable<System.DateTime> next_arm_change_date { get; set; }
        public Nullable<decimal> expected_interest_rate { get; set; }
        public Nullable<decimal> interest_rate_at_closing { get; set; }
        public decimal mip_rate { get; set; }
        public Nullable<decimal> margin { get; set; }
        public Nullable<bool> rounding { get; set; }
        public Nullable<decimal> interest_rate_lifetime_max { get; set; }
        public Nullable<decimal> interest_rate_max_from_closing_rate { get; set; }
        public Nullable<decimal> interest_rate_max_from_current_rate { get; set; }
        public Nullable<decimal> previous_interest_rate { get; set; }
        public Nullable<decimal> current_interest_rate { get; set; }
        public Nullable<decimal> next_interest_rate { get; set; }
        public Nullable<decimal> previous_rate_index { get; set; }
        public Nullable<decimal> current_rate_index { get; set; }
        public Nullable<decimal> next_rate_index { get; set; }
        public Nullable<System.DateTime> index_publish_date { get; set; }
        public Nullable<decimal> debenture_interest_rate { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<bool> round_to_one_eighth_flag { get; set; }
    }
}
