//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_hmbs_pool_loan
    {
        public int hmbs_pool_loan_skey { get; set; }
        public int hmbs_pool_skey { get; set; }
        public int loan_skey { get; set; }
        public string ginnie_mae_number { get; set; }
        public string participation_id { get; set; }
        public decimal interest_rate { get; set; }
        public Nullable<decimal> service_fee_margin { get; set; }
        public Nullable<decimal> participation_opb_amount { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
