//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_message
    {
        public int log_message_skey { get; set; }
        public Nullable<int> log_message_type_skey { get; set; }
        public string message_severity { get; set; }
        public string log_message1 { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
    
        public virtual ref_log_message_type ref_log_message_type { get; set; }
    }
}
