//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_qc_sub_status
    {
        public int qc_sub_status_skey { get; set; }
        public int product_type_skey { get; set; }
        public string boarding_type { get; set; }
        public string qc_or_review { get; set; }
        public string match_sub_status { get; set; }
        public string mismatch_sub_status { get; set; }
        public string unconfirmed_status { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
