//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_loan_pool
    {
        public int loan_pool_skey { get; set; }
        public string loan_pool_short_description { get; set; }
        public string loan_pool_long_description { get; set; }
        public int investor_skey { get; set; }
        public string msr_type { get; set; }
        public string check_payable_to { get; set; }
        public string aba_number { get; set; }
        public string account_number { get; set; }
        public Nullable<bool> flow_loan_pool_flag { get; set; }
        public Nullable<int> statement_file_skey { get; set; }
        public Nullable<bool> generate_statements_flag { get; set; }
        public Nullable<int> rff_group_skey { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
