//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_app_parameter
    {
        public string application_name { get; set; }
        public bool production_flag { get; set; }
        public bool application_locked_flag { get; set; }
        public Nullable<int> login_lock_days { get; set; }
        public Nullable<int> password_history_count { get; set; }
        public Nullable<int> password_expiration_days { get; set; }
        public Nullable<int> password_change_remider_days { get; set; }
        public Nullable<int> maximum_attachment_file_size_in_mb { get; set; }
        public Nullable<decimal> initial_mip_tolerance_amount { get; set; }
        public Nullable<decimal> minimum_allowed_rate { get; set; }
        public Nullable<decimal> maximum_allowed_rate { get; set; }
        public Nullable<bool> monthend_initialized { get; set; }
        public Nullable<bool> monthend_accrual_completed { get; set; }
        public Nullable<bool> monthend_sfsa_completed { get; set; }
        public Nullable<bool> monthend_growth_completed { get; set; }
        public Nullable<bool> monthend_non_hecm_completed { get; set; }
        public Nullable<bool> monthend_disbursement_completed { get; set; }
        public Nullable<bool> monthend_final_completed { get; set; }
        public Nullable<decimal> repair_administration_fee_percent { get; set; }
        public Nullable<decimal> repair_administration_fee_minimum_amount { get; set; }
        public Nullable<decimal> maximum_change_of_plan_fee_amount { get; set; }
        public Nullable<decimal> hmbs_guaranty_fee_rate { get; set; }
        public Nullable<int> tenure_age { get; set; }
    }
}
