//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_loan_sub_status
    {
        public string loan_sub_status_code { get; set; }
        public string loan_sub_status_description { get; set; }
        public string loan_status_code { get; set; }
        public Nullable<int> loan_sub_status_hierarchy { get; set; }
        public Nullable<bool> FNMA_accrual_required { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
