//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_auto_job
    {
        public int auto_job_skey { get; set; }
        public string auto_job_description { get; set; }
        public bool run_sunday_flag { get; set; }
        public bool run_monday_flag { get; set; }
        public bool run_tuesday_flag { get; set; }
        public bool run_wednesday_flag { get; set; }
        public bool run_thursday_flag { get; set; }
        public Nullable<bool> run_friday_flag { get; set; }
        public bool run_saturday_flag { get; set; }
        public string unprocessed_folder { get; set; }
        public string processed_folder { get; set; }
        public string duplicate_folder { get; set; }
        public string invalid_folder { get; set; }
        public string primary_email { get; set; }
        public string secondary_email { get; set; }
        public string other_email { get; set; }
        public string job_type { get; set; }
        public Nullable<int> monthly_job_day_number { get; set; }
        public Nullable<bool> is_business_day_flag { get; set; }
        public Nullable<bool> is_saturday_business_day_flag { get; set; }
        public Nullable<bool> part_of_allinterfaces_job_flag { get; set; }
        public Nullable<bool> is_import_job_flag { get; set; }
        public string file_name_format_code { get; set; }
        public string document_type_mapping_code { get; set; }
        public Nullable<bool> show_report_criteria_flag { get; set; }
        public string servicer_skeys { get; set; }
        public string investor_skeys { get; set; }
        public string pool_skeys { get; set; }
        public string loan_status { get; set; }
        public string loan_sub_status { get; set; }
        public string ftp_http_server { get; set; }
        public string ftp_user_id { get; set; }
        public string ftp_pwd { get; set; }
        public string ftp_folder { get; set; }
        public string smtp_server { get; set; }
        public Nullable<int> smtp_port { get; set; }
        public string smtp_userid { get; set; }
        public string smtp_pwd { get; set; }
        public string smtp_domain { get; set; }
        public string winscp_path { get; set; }
        public string sftp_logfile_path { get; set; }
        public string sftp_send_receive { get; set; }
        public string sftp_copy_move_file { get; set; }
        public Nullable<int> run_sftp { get; set; }
        public string hecm_nonhecm_ind { get; set; }
        public Nullable<System.DateTime> current_monthend_date { get; set; }
        public string job_details { get; set; }
        public string job_function { get; set; }
        public string process_type { get; set; }
        public string package_filename { get; set; }
        public string config_filename { get; set; }
        public string filename { get; set; }
        public string staging_table_name { get; set; }
        public string source_proc_name { get; set; }
        public string post_process_proc_name { get; set; }
        public string source_data { get; set; }
        public string contact_name { get; set; }
        public string contact_email { get; set; }
        public string contact_phone { get; set; }
        public string job_execution_status { get; set; }
        public string job_execution_status_description { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<bool> is_import_document_job_flag { get; set; }
        public Nullable<bool> run_sftp_flag { get; set; }
    }
}
