//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_state
    {
        public string state_code { get; set; }
        public string state_name { get; set; }
        public Nullable<int> hoc_skey { get; set; }
        public string zip_code_format { get; set; }
        public Nullable<int> average_default_period { get; set; }
        public Nullable<int> average_foreclosure_period { get; set; }
        public Nullable<int> average_reo_period { get; set; }
        public Nullable<int> average_claim_period { get; set; }
        public Nullable<int> non_judicial_foreclosure_period { get; set; }
        public Nullable<int> judicial_foreclosure_period { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
