//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_workflow_task_client_config
    {
        public int client_skey { get; set; }
        public int workflow_task_skey { get; set; }
        public int workflow_data_group_skey { get; set; }
        public string workflow_task_type { get; set; }
        public int sequence_number { get; set; }
        public Nullable<int> estimated_days_from_initiation_to_start { get; set; }
        public Nullable<int> estimated_days_from_initiation_to_due { get; set; }
        public string letter_name { get; set; }
        public bool requires_task_result_flag { get; set; }
        public bool auto_complete_flag { get; set; }
        public bool lock_start_date_flag { get; set; }
        public Nullable<int> start_date_notification_email_template_skey { get; set; }
        public Nullable<int> due_date_notification_email_template_skey { get; set; }
        public Nullable<int> email_notification_days_before_start_date { get; set; }
        public Nullable<int> email_notification_days_before_due_date { get; set; }
        public Nullable<int> auto_note_skey { get; set; }
        public Nullable<int> alert_type_skey { get; set; }
        public Nullable<int> document_type_skey { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
