//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_county_clerk
    {
        public int county_clerk_skey { get; set; }
        public string county_clerk_name { get; set; }
        public string pay_to_name { get; set; }
        public string attention_to { get; set; }
        public string county_address1 { get; set; }
        public string county_address2 { get; set; }
        public string county_city { get; set; }
        public string state_code { get; set; }
        public string county_zip_code { get; set; }
        public Nullable<System.DateTime> poa_recorded_date { get; set; }
        public string poa_book_number { get; set; }
        public string poa_page_number { get; set; }
        public string poa_instrument_number { get; set; }
        public Nullable<System.DateTime> poa_sent_for_recording_date { get; set; }
        public string recording_fee_information { get; set; }
        public decimal first_page_rec_fee_amount { get; set; }
        public decimal additional_page_rec_fee_amount { get; set; }
        public decimal mers_rec_fee_amount { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
