//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_client
    {
        public int client_skey { get; set; }
        public string client_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state_code { get; set; }
        public string zip_code { get; set; }
        public Nullable<decimal> main_phone_number { get; set; }
        public Nullable<decimal> alt_phone_number { get; set; }
        public Nullable<decimal> fax_number { get; set; }
        public string email { get; set; }
        public string website_url { get; set; }
        public int status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
