//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Securitydata
    {
        public string data_group_skey { get; set; }
        public string client_skey { get; set; }
        public string loan_servicer_skey { get; set; }
        public string investor_skey { get; set; }
        public string loan_pool_skey { get; set; }
        public string status_skey { get; set; }
        public string created_date { get; set; }
        public string created_by { get; set; }
    }
}
