//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_ssrs_print_vendor_import
    {
        public int loan_skey { get; set; }
        public int contact_skey { get; set; }
        public Nullable<int> document_type_skey { get; set; }
        public string certified_article_number { get; set; }
        public Nullable<System.DateTime> date_mailed { get; set; }
        public Nullable<int> page_count { get; set; }
        public Nullable<bool> processed_flag { get; set; }
        public Nullable<bool> requested_flag { get; set; }
        public Nullable<bool> responded_flag { get; set; }
        public Nullable<int> import_file_skey { get; set; }
        public string attachment_file_name { get; set; }
    }
}
