//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReverseQuest.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class su
    {
        public string user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<decimal> phone_number { get; set; }
        public Nullable<decimal> fax_number { get; set; }
        public string email { get; set; }
        public Nullable<bool> show_critical_alerts { get; set; }
        public Nullable<bool> show_in_select_list { get; set; }
        public int client_skey { get; set; }
        public Nullable<int> data_group_skey { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public Nullable<System.DateTime> last_password_change_date { get; set; }
        public Nullable<bool> locked_flag { get; set; }
        public Nullable<int> status_skey { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    }
}
